CREATE DATABASE Bd_Taxi_AndresVillalobos

USE Bd_Taxi_AndresVillalobos

CREATE TABLE Chofer (
IdChofer INT PRIMARY KEY NOT NULL,
Licencia VARCHAR(50) NOT NULL,
Nombre VARCHAR(50) NOT NULL,
Apellidos VARCHAR (50) NOT NULL,
Estado bit NOT NULL
)
CREATE TABLE Taxi (
IdTaxi INT PRIMARY KEY NOT NULL,
IdChofer INT NOT NULL,
Placa VARCHAR(50) NOT NULL,
Capacidad TINYINT NOT NULL,
Estado BIT NOT NULL
)
CREATE TABLE Factura (
IdFactura INT PRIMARY KEY NOT NULL,
IdServicio INT NOT NULL,
FechaPago DATE NOT NULL,
Monto INT NOT NULL,
Estado bit NOT NULL
)
CREATE TABLE Servicio (
IdServicio INT PRIMARY KEY NOT NULL,
Fecha SMALLDATETIME,
IdTaxi INT NOT NULL,
IdCliente INT NOT NULL,
Kilometraje INT NOT NULL,
Estado CHAR(1) NOT NULL
)
CREATE TABLE Cliente (
IdCliente INT PRIMARY KEY NOT NULL,
Nombre VARCHAR(50) NOT NULL,
Apellidos VARCHAR(50) NOT NULL,
Telefono INT NOT NULL,
Direccion VARCHAR(250) NOT NULL
)


ALTER TABLE Chofer
ADD CONSTRAINT PK_Chofer PRIMARY KEY (IdChofer)
ALTER TABLE Taxi
ADD CONSTRAINT PK_Taxi PRIMARY KEY (IdTaxi)
ALTER TABLE Factura
ADD CONSTRAINT PK_Factura PRIMARY KEY (IdFactura)
ALTER TABLE Servicio
ADD CONSTRAINT PK_Servicio PRIMARY KEY (IdServicio)
ALTER TABLE Cliente
ADD CONSTRAINT PK_CLiente PRIMARY KEY (IdCliente)
ALTER TABLE Taxi
	ADD CONSTRAINT FK_Chofer FOREIGN KEY (IdChofer) REFERENCES Chofer (IdChofer)

ALTER TABLE Servicio
	ADD CONSTRAINT FK_Taxi FOREIGN KEY (IdTaxi) REFERENCES Taxi (IdTaxi)
ALTER TABLE Servicio
	ADD CONSTRAINT FK_Cliente FOREIGN KEY (IdCliente) REFERENCES Cliente (IdCliente)
ALTER TABLE Servicio
ADD CONSTRAINT CHk_Estado CHECK (Estado IN ('P', 'C', 'E'));
ALTER TABLE Factura
	ADD CONSTRAINT FK_Servicio FOREIGN KEY (IdServicio) REFERENCES Servicio (IdServicio)
